---
title: "Countries_Clustering_covid19"
date: '2022-08-25'
output: rmarkdown::github_document
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
```

```{r}
file <- file.path("..", "covid_19_project", "data.csv")
data <- read.csv(file)
head(data)
```

```{r}
NPI_12 <- data %>%
                    select(Country, Date, Measure_L2)
```

```{r}
NPI_12_ML2_rec <- NPI_12 %>% mutate(Measure_L2_recode =recode(Measure_L2,
                                                         "Activate case notification"= 1,
                                                         "Airport health check"= 2,
                                                         "Border health check" = 3,
                                                         "Enhance detection system"= 4,
                                                         "Isolation of cases"= 5,
                                                         "Quarantine"= 6,
                                                         "Restricted testing"= 7,
                                                         "Surveillance"= 8,
                                                         "Tracing and tracking"=9,
                                                         
                                                         
                                                         "Enhance hygiene conditions"= 10,
                                                         "Environmental cleaning and disinfection"= 11,
                                                         
                                                         
                                                         "Adapt procedures for patient management"= 12,
                                                         "Enhance laboratory testing capacity"= 13,
                                                         "Increase availability of PPE"= 14,
                                                         "Increase healthcare workforce"= 15,
                                                         "Increase in medical supplies and equipment"= 16,
                                                         "Increase isolation and quarantine facilities"= 17,
                                                         "Increase patient capacity"= 18,
                                                         "Personal protective measures"= 19,
                                                         "Repurpose hospitals"= 20,
                                                         "Research"= 21,
                                                         
                                                         
                                                         "Closure of educational institutions"=22,
                                                         "Measures for public transport"= 23,
                                                         "Public transport restriction"=24,
                                                         "Measures for special populations"=25,
                                                         "Special measures for certain establishments"= 26,
                                                         "Work safety protocols"= 27,
                                                         "Indoor and outdoor gathering restriction"=28,
                                                         "Indoor gathering restriction"=29,
                                                         "Outdoor gathering restriction"=30,
                                                         
                                                         
                                                         "Actively communicate with healthcare professionals"= 31,
                                                         "Actively communicate with managers"= 32,
                                                         "Educate and actively communicate with the public"=33,
                                                         "Travel alert and warning"= 34,
                                                         
                                                         
                                                         "Activate or establish emergency response"=35,
                                                         "Crisis management plans"= 36,
                                                         "Economic measure to stimulate consumption"=37,
                                                         "Measures to ensure security of supply"= 38,
                                                         "Police and army interventions"=39,
                                                         "Provide international help"=40,
                                                         "Receive international help"= 41,
                                                         "The government provide assistance to vulnerable populations"= 42,
                                                         
                                                         
                                                         "Airport restriction"= 43,
                                                         "Border restriction"=44,
                                                         "Cordon sanitaire"= 45,
                                                         "Individual movement restrictions"=46,
                                                         "National lockdown"=47,
                                                         "Port and ship restriction"= 48,
                                                         
                                                         
                                                         "Access to non-essential/critical healthcare services"= 49,
                                                         "Exemption of quarantine"= 50,
                                                         "Re-opening educational institutions"= 51,
                                                         "Lift airport restrictions"= 52,
                                                         "Lift personal protective measures"= 53,
                                                         "Lift restriction on individual movements"=54,
                                                         "Lift restriction on public transports"= 55,
                                                         "Lift travel restriction"= 56,
                                                         "Phase out emergency management"= 57,
                                                         "Re-opening of educational institutions"= 58,
                                                         "Lift measures to protect vulnerable populations"= 59,
                                                         "Lift restriction on indoor gatherings"=60,
                                                         "Lift border restrictions"= 61,
                                                         "Lift restriction on outdoor gatherings"= 62,
                                                         "Secure future access to anti-Covid19 medication and vaccine"= 63,
                                                         "Special measures for certain establishments"= 64,
                                                         "Lift restriction on indoor and outdoor gatherings" = 65,
                                                         "Lift restriction on indoor-gatherings"= 66,
                                                         "Relax detection system"= 67,
                                                         "Lift restrictions on outdoor gatherings"= 68,
                                                         "Lift restrictions on indoor and outdoor gatherings"= 69,
                                                         "Lift restricton on outdoor gatherings"= 70,
                                                         "Resume export of medical and personal protective equipment"= 71 )) 
```

```{r}
head(NPI_12_ML2_rec)
```

```{r}
## Remove Measure_L2 and continent columns:  
NPI_12.recode <-NPI_12_ML2_rec [,c(1,2,4)] 
head(NPI_12.recode, 6)
```

```{r}
## Set date from January 2020 to May 2020
# To include all Countries, 
#because some Country contain data until May 2020;
NPI_May.recode <- NPI_12.recode[NPI_12.recode$Date >= "2020-01-01" &    # Extract data frame subset
                              NPI_12.recode$Date <= "2020-05-31", ]

NPI_May.recode
```

```{r}
NPI_May.recode$Measure_L2_recode <- as.character(NPI_May.recode$Measure_L2_recode)
NPI_May.recode
```

```{r}
NPI_May.recode.g <- NPI_May.recode %>% 
  group_by(Country,Date) %>%
  summarise(Measure_L2_recode = paste0(unique(Measure_L2_recode),collapse="-"))
  NPI_May.recode.g <- NPI_May.recode.g
  

NPI_May.recode.g
```

```{r}
gfg <- "30-6-43-44"
#res <- as.numeric(gsub(".*?([0-9]+).*", "\\1", gfg))   

#gfg_numbers <- regmatches(gfg, gregexpr("[[:digit:]]+", gfg))
#as.numeric(unlist(gfg_numbers))

library(tidyr)
library(readr)

Numbers_Handling <-  function(nums_str) {
  extracted_nums <-  regmatches(nums_str, gregexpr("[[:digit:]]+",nums_str))
  ordered_number <- paste(sort((as.numeric(unlist(extracted_nums)))), collapse="-")
  return(ordered_number)
}
```

```{r}
NPI_May.recode.g <- NPI_May.recode.g %>%
    mutate(Measure_L2_recode = sapply(Measure_L2_recode, Numbers_Handling))
NPI_May.recode.g
```

```{r}
## pivot_wider Country >> column
NPI_May.wider_with_na <- NPI_May.recode.g %>% pivot_wider(names_from ="Country",
                                         values_from="Measure_L2_recode")

NPI_May.wider_with_na
```

```{r}
## Replace missing value NA of NPI with 0:   
NPI_May.wider <- mutate_at(NPI_May.wider_with_na, c(2:59), ~replace(., is.na(.), 0))
DF <- NPI_May.wider
```

```{r}
DF[sapply(DF, is.character)] <- lapply(DF[sapply(DF, is.character)], 
                                       as.factor)

DF
```

```{r}
library(cluster)
df<-DF
# calculate distance
d_dist<-daisy(df, metric = "gower")
# hierarchical clustering
hc<-hclust(d_dist, method = "complete")
# dendrogram 
plot(hc, labels=FALSE)
rect.hclust(hc, k=8, border="red")
# choose k, number of clusters 
cluster<-cutree(hc, k=8)
# add cluster to original data 
df<-cbind(df,as.factor(cluster))
```

```{r}
df
```

```{r}
library(factoextra)

# Elbow method
fviz_nbclust(DF, hcut, method = "wss") +
  geom_vline(xintercept = 4, linetype = 2)+
  labs(subtitle = "Elbow method")
```

```{r}

library(cluster)
df<-DF
# calculate distance
d_dist<-daisy(df, metric = "gower")
# hierarchical clustering
hc<-hclust(d_dist, method = "complete")
# dendrogram 
plot(hc, labels=FALSE)
rect.hclust(hc, k=4, border="red")
# choose k, number of clusters 
cluster<-cutree(hc, k=4)
# add cluster to original data 
df<-cbind(df,as.factor(cluster))
```
